// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/traffic.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TrafficService_SendConnectionEvents_FullMethodName = "/traffic.TrafficService/SendConnectionEvents"
	TrafficService_HealthCheck_FullMethodName          = "/traffic.TrafficService/HealthCheck"
)

// TrafficServiceClient is the client API for TrafficService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrafficServiceClient interface {
	SendConnectionEvents(ctx context.Context, opts ...grpc.CallOption) (TrafficService_SendConnectionEventsClient, error)
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type trafficServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrafficServiceClient(cc grpc.ClientConnInterface) TrafficServiceClient {
	return &trafficServiceClient{cc}
}

func (c *trafficServiceClient) SendConnectionEvents(ctx context.Context, opts ...grpc.CallOption) (TrafficService_SendConnectionEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &TrafficService_ServiceDesc.Streams[0], TrafficService_SendConnectionEvents_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &trafficServiceSendConnectionEventsClient{stream}
	return x, nil
}

type TrafficService_SendConnectionEventsClient interface {
	Send(*ConnectionBatch) error
	CloseAndRecv() (*ConnectionResponse, error)
	grpc.ClientStream
}

type trafficServiceSendConnectionEventsClient struct {
	grpc.ClientStream
}

func (x *trafficServiceSendConnectionEventsClient) Send(m *ConnectionBatch) error {
	return x.ClientStream.SendMsg(m)
}

func (x *trafficServiceSendConnectionEventsClient) CloseAndRecv() (*ConnectionResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ConnectionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *trafficServiceClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, TrafficService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrafficServiceServer is the server API for TrafficService service.
// All implementations must embed UnimplementedTrafficServiceServer
// for forward compatibility
type TrafficServiceServer interface {
	SendConnectionEvents(TrafficService_SendConnectionEventsServer) error
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedTrafficServiceServer()
}

// UnimplementedTrafficServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTrafficServiceServer struct {
}

func (UnimplementedTrafficServiceServer) SendConnectionEvents(TrafficService_SendConnectionEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method SendConnectionEvents not implemented")
}
func (UnimplementedTrafficServiceServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedTrafficServiceServer) mustEmbedUnimplementedTrafficServiceServer() {}

// UnsafeTrafficServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrafficServiceServer will
// result in compilation errors.
type UnsafeTrafficServiceServer interface {
	mustEmbedUnimplementedTrafficServiceServer()
}

func RegisterTrafficServiceServer(s grpc.ServiceRegistrar, srv TrafficServiceServer) {
	s.RegisterService(&TrafficService_ServiceDesc, srv)
}

func _TrafficService_SendConnectionEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TrafficServiceServer).SendConnectionEvents(&trafficServiceSendConnectionEventsServer{stream})
}

type TrafficService_SendConnectionEventsServer interface {
	SendAndClose(*ConnectionResponse) error
	Recv() (*ConnectionBatch, error)
	grpc.ServerStream
}

type trafficServiceSendConnectionEventsServer struct {
	grpc.ServerStream
}

func (x *trafficServiceSendConnectionEventsServer) SendAndClose(m *ConnectionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *trafficServiceSendConnectionEventsServer) Recv() (*ConnectionBatch, error) {
	m := new(ConnectionBatch)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TrafficService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficServiceServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrafficService_ServiceDesc is the grpc.ServiceDesc for TrafficService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrafficService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "traffic.TrafficService",
	HandlerType: (*TrafficServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _TrafficService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendConnectionEvents",
			Handler:       _TrafficService_SendConnectionEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/traffic.proto",
}
